# Generated by Django 4.1.7 on 2024-06-10 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
                ('id_auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InformesFinancieros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(max_length=20)),
                ('organizacion_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_contraloria.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descripcion', models.CharField(max_length=250)),
                ('id_presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_contraloria.presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('recomendacion', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=20)),
                ('id_auditoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_contraloria.auditoria')),
            ],
        ),
        migrations.AddField(
            model_name='auditoria',
            name='organizacion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_contraloria.organizacion'),
        ),
    ]
