# Generated by Django 4.1.7 on 2024-06-24 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacion_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_contraloria.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(max_length=20)),
                ('organizacion_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_contraloria.organizacion')),
                ('reporte_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_contraloria.reporte')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.userperfil')),
            ],
        ),
    ]
