# Generated by Django 4.1.7 on 2024-06-24 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Organizacion',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresos_anuales', models.IntegerField()),
                ('costos_fijos', models.IntegerField()),
                ('costos_variables', models.IntegerField()),
                ('gastos_de_capital', models.IntegerField()),
                ('metas_corto_largo_plazo', models.CharField(max_length=50)),
                ('proyectos', models.IntegerField()),
                ('condiciones_económicas', models.CharField(max_length=50)),
                ('deudas_actuales', models.IntegerField()),
                ('personal', models.IntegerField()),
                ('costos_de_ersonal', models.IntegerField()),
                ('necesidades_tecnológicas', models.CharField(max_length=50)),
                ('reservas_de_contingencia', models.IntegerField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('organizacion_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_contraloria.organizacion')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
    ]
