# Generated by Django 5.0.6 on 2024-06-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_contraloria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='id_auditor',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='organizacion_id',
        ),
        migrations.RemoveField(
            model_name='hallazgo',
            name='id_auditoria',
        ),
        migrations.DeleteModel(
            name='InformesFinancieros',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='organizacion_id',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='id_presupuesto',
        ),
        migrations.DeleteModel(
            name='Auditoria',
        ),
        migrations.DeleteModel(
            name='Hallazgo',
        ),
        migrations.DeleteModel(
            name='Organizacion',
        ),
        migrations.DeleteModel(
            name='Presupuesto',
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
    ]
