# Generated by Django 4.1.7 on 2024-06-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_contraloria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizacion',
            options={'verbose_name': 'Organización', 'verbose_name_plural': 'Organizaciones'},
        ),
        migrations.AddField(
            model_name='organizacion',
            name='en_supervision',
            field=models.BooleanField(default=False),
        ),
    ]
