# Generated by Django 4.1.7 on 2024-06-25 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_contraloria', '0002_alter_organizacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='en_supervision',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
