# Generated by Django 5.0.6 on 2024-06-17 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_contraloria', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 6, 17, 21, 46, 20, 304100, tzinfo=datetime.timezone.utc)),
        ),
    ]
