# Generated by Django 5.0.6 on 2024-06-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_contraloria', '0004_alter_presupuesto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
