# Generated by Django 4.1.7 on 2024-06-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_contraloria', '0006_alter_reporte_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
