# Generated by Django 4.1.7 on 2024-06-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_contraloria', '0007_alter_reporte_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='costos_fijos',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='costos_variables',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='metas_corto_largo_plazo',
        ),
    ]
