# Generated by Django 4.1.7 on 2024-06-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_contraloria', '0008_remove_reporte_costos_fijos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='condiciones_económicas',
        ),
    ]
