# Generated by Django 4.1.7 on 2024-07-09 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_contraloria', '0010_remove_reporte_necesidades_tecnológicas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='organizacion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_contraloria.organizacion'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
