# Generated by Django 4.1.7 on 2024-07-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_contraloria', '0011_alter_reporte_organizacion_id_alter_reporte_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
