# Generated by Django 5.0.6 on 2024-06-22 21:38

import django.contrib.auth.models
import django.db.models.deletion
import user.models
import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userperfil',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_user', models.CharField(default='', max_length=100, verbose_name='Nombre completo*')),
                ('foto', models.ImageField(default='', help_text='Archivos permitidos: Solamente imágenes', upload_to=user.models.user_directory_path, validators=[user.validators.valid_foto])),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_user', to='user.userperfil', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
