# Generated by Django 5.0.6 on 2024-06-18 04:58

import django.db.models.deletion
import user.models
import user.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_user', models.CharField(default='', max_length=100, verbose_name='Nombre completo*')),
                ('foto', models.ImageField(default='', help_text='Archivos permitidos: Solamente imágenes', upload_to=user.models.user_directory_path, validators=[user.validators.valid_foto])),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
